
server:
  port: 8080
  wechat-api-url:
  wechat-js-api-debug: false
  wechat-js-api-beta: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  profiles:
    active: dev
  application:
    name: nft
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    database: 1



mybatis-plus:
  mapperLocations: classpath*:mapping/*.xml
  typeAliasesPackage: com.ntf.ntf_project.model.*
  configuration:
    mapUnderscoreToCamelCase: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  config: classpath:log4j2-spring.xml
  level:
    com.iyiou.yiou: error
    springfox.documentation: error
    org.mybatis: error
    org.apache: error
    com.alibaba: error
    com.netflix: error
    org.springframework: info
    org.quartz: error
    cn.jay.repository: trace
    org.springframework.boot.autoconfigure: ERROR

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"