
spring:
  profiles: dev
  webConfig:
    name: nft
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: mysql
    url: jdbc:mysql://127.0.0.1:3306/crm_test?useUnicode=yes&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 500
    # 配置获取连接等待超时的时间
    maxWait: 6000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    maxEvictableIdleTimeMillis: 600000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  redis:
    host: 192.168.30.7
    password: Iyiou@2020
    port: 6379
    database: 2
    timeout: 30000
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        time-between-eviction-runs: -1 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1

  mail:
    host: smtp.qq.com
    username: 296580640@qq.com
    password: tspghiptcrxbbgce
    properties:
      mail:
        smtp:
          port: 465
          starttls:
            enable: true
            required: true
          connectiontimeout: 6000
          timeout: 5000
          writetimeout: 5000
          ssl:
            enable: true
    default-encoding: UTF-8

  config:
    ##jwt配置
    jwt:
      # 代表这个JWT的接收对象,存入audience
      clientId: 2f77bd9e492430a3
      # 密钥, 经过Base64加密, 可自行替换
      base64Secret: SXlpb3VAMjAyMA==
      # JWT的签发主体，存入issuer
      name: iyiouapiuser
      # 过期时间，时间戳
      expiresSecond: 7776000000
  security:
    user:
      name: iyiou
      password: 2f77bd9e492430a3

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis-plus:
  mapperLocations: classpath*:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  typeAliasesPackage: com.iyiou.yiou.*.*.model.*.*  # 注意：对应实体类的路径
  configuration:
    mapUnderscoreToCamelCase: true
    cache-enabled: false

## 日志输出范围配置
debug: true
logging:
  #config: classpath:log4j2.xml
  #file: serverUser.log
  level:
    com.iyiou.yiou: debug
swagger:
  enabled: true